# This is a basic workflow to help you get started with Actions

name: Basis Continuous Integration (CI) 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]
# Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  
jobs:
  test-and-publish:
    name: Run unit tests
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t coloring_microservice:latest
      
      - name: Run Django tests
        run: docker container run --rm -e command="python manage.py test" coloring_microservice:latest

      - name: Log in to Docker Hub
        if: ${{ github.event_name == 'push' }}
        run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Tag the built image
        run: docker tag coloring_microservice:latest ${{ secrets.DOCKERHUB_USERNAME }}/coloring_microservice:latest

      - name: Push to Docker hub
        if: ${{ github.event_name == 'push' }}
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/coloring_microservice:latest
