# This is a basic workflow to help you get started with Actions

name: Basis Continuous Integration (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  testing:
    name: Run unit tests
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build --no-cache . -t ColoringMicroservice:latest
      
      - name: Run docker container
        run: docker container run --rm -v ./ColoringMicroservice:/ColoringMicroservice ColoringMicroservice
