# This is a basic workflow to help you get started with Actions

name: Basis Continuous Integration (CI)  1

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
# Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
  
jobs:
  test-and-publish:
    name: Run unit tests
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #   with:
      #     lfs: true
      # - name: Checkout LFS objects
      #   run: git lfs checkout
        
      # - name: Build docker image
      #   run: docker build . -t coloring_microservice:latest
      # Github made me use this ...
      - name: Stitch together broken models
        run: |
        cat ./ColorizationApi/Models/0.gz.part* > ./ColorizationApi/Models/non_fastai_model.pt &&
        cat ./ColorizationApi/Models/1.gz.part* > ./ColorizationApi/Models/fastai_model_20.pt &&
        cat ./ColorizationApi/Models/2.gz.part* > ./ColorizationApi/Models/fastai_model_40.pt &&
        cat ./ColorizationApi/Models/1.1.gz.part* > ./ColorizationApi/Models/res18_unet_20.pt &&
        cat ./ColorizationApi/Models/2.1.gz.part* > ./ColorizationApi/Models/res18_unet_40.pt
      
      - name: Run Django tests
        run: docker container run --rm -e command="python manage.py test" coloring_microservice:latest

      - name: Log in to Docker Hub
        if: ${{ github.event_name == 'push' }}
        run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password=${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Tag the built image
        run: docker tag coloring_microservice:latest ${{ secrets.DOCKERHUB_USERNAME }}/coloring_microservice:latest

      - name: Push to Docker hub
        if: ${{ github.event_name == 'push' }}
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/coloring_microservice:latest
